services:
  php-raw:
    restart: always
    image: docker.io/php:8.3-cli
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "8787:8081"
    command: sh -c "cd /var/www/html && php -S 0.0.0.0:8081"
  php-fpm:
    restart: always
    image: docker.io/php:8.3-fpm
    volumes:
      - ./src/:/var/www/html/
      - ./docker/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf
    command: sh -c "php-fpm -F"
  nginx:
    restart: always
    image: docker.io/nginx:1.27.2
    volumes:
      - ./src/:/var/www/html/
      - ./docker/core_nginx.conf:/etc/nginx/nginx.conf
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8888:80"
  nginx-fastcgi-cache:
    restart: always
    image: docker.io/nginx:1.27.2
    volumes:
      - ./src/:/var/www/html/
      - ./docker/core_nginx_fast.conf:/etc/nginx/nginx.conf
      - ./docker/default_fast.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8989:80"
